// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFeatures: typeof import('./src/components/Home/AppFeatures.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    UserProfile: typeof import('./src/components/Home/UserProfile.vue')['default']
    UsersList: typeof import('./src/components/Home/UsersList.vue')['default']
  }
}

export {}
